import type { Metadata } from 'next'
import { Arima } from 'next/font/google'
import './globals.css'
import { Providers } from '@/redux/provider'

const arima = Arima({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
    <html lang="en">
      <body className={arima.className}>{children}</body>
    </html>
    </Providers>
  )
}
